# Generated by Django 3.0.8 on 2020-07-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedatabase',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
