# Generated by Django 3.0.8 on 2020-08-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20200725_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedatabase',
            name='recommendation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
