# Generated by Django 3.0.8 on 2020-08-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_moviedatabase_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('title', models.TextField()),
                ('tagline', models.TextField()),
                ('description', models.TextField()),
                ('genres', models.TextField()),
                ('keywords', models.TextField()),
                ('date', models.TextField()),
                ('collection', models.TextField()),
                ('runtime', models.TextField()),
                ('revenue_budget', models.TextField()),
                ('director', models.TextField()),
                ('cast', models.TextField()),
                ('production_companies', models.TextField()),
                ('production_countries', models.TextField()),
                ('popularity', models.TextField()),
                ('average_vote', models.TextField()),
                ('num_votes', models.TextField()),
                ('language', models.TextField()),
                ('imdb_id', models.TextField()),
                ('poster_url', models.TextField()),
            ],
        ),
    ]
