# Generated by Django 3.0.8 on 2020-08-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_moviedb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedb',
            name='average_vote',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='date',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='description',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='director',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='imdb_id',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='language',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='num_votes',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='production_companies',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='production_countries',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='revenue_budget',
        ),
        migrations.RemoveField(
            model_name='moviedb',
            name='runtime',
        ),
    ]
