# Generated by Django 3.0.8 on 2020-08-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_remove_moviedatabase_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentrec',
            name='average_vote',
        ),
        migrations.RemoveField(
            model_name='contentrec',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='contentrec',
            name='id1',
        ),
        migrations.RemoveField(
            model_name='contentrec',
            name='num_votes',
        ),
        migrations.RemoveField(
            model_name='contentrec',
            name='popularity',
        ),
    ]
