# Generated by Django 3.0.8 on 2020-08-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_auto_20200816_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('genres', models.TextField()),
                ('keywords', models.TextField()),
                ('popularity', models.TextField()),
                ('average_vote', models.TextField()),
                ('num_votes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='DB',
        ),
    ]
